import { useCallback, useEffect, useMemo, useState } from "react";
import { fetchResults, fetchStatus } from "./lib/api.js";
import { buildModel } from "./lib/model.js";
import { hrefs } from "./lib/router.js";
import { useRoute } from "./lib/useRoute.js";
import Dashboard from "./views/Dashboard.jsx";
import CandidateDetail from "./views/CandidateDetail.jsx";
import Compare from "./views/Compare.jsx";
import Rejected from "./views/Rejected.jsx";
import Failed from "./views/Failed.jsx";
import SelectionTray from "./components/SelectionTray.jsx";
import { Loading, ErrorState } from "./components/States.jsx";

export default function App() {
  const route = useRoute();
  const [results, setResults] = useState(null);
  const [source, setSource] = useState(null);
  const [error, setError] = useState(null);
  const [selected, setSelected] = useState([]);

  const load = useCallback(() => {
    setError(null); setResults(null);
    fetchResults().then(setResults).catch(setError);
    fetchStatus().then(setSource);
  }, []);
  useEffect(load, [load]);

  const model = useMemo(() => (results ? buildModel(results) : null), [results]);
  const toggle = useCallback((file) => setSelected((s) => (s.includes(file) ? s.filter((f) => f !== file) : s.length >= 3 ? s : [...s, file])), []);
  // Keep the tray and the comparison URL in step when arriving on a comparison link.
  const routeFiles = route.name === "compare" ? route.files.join("|") : "";
  useEffect(() => { if (routeFiles) setSelected(routeFiles.split("|").slice(0, 3)); }, [routeFiles]);

  const nav = (name, label, href, count) => (
    <a href={href} aria-current={route.name === name || (name === "dashboard" && route.name === "candidate") ? "page" : undefined}>{label}{count !== undefined ? <span className="count num">{count}</span> : null}</a>
  );

  return (
    <div className="shell">
      <div className="topbar">
        <a className="brand" href={hrefs.dashboard()} aria-label="Screening console home">
          <span className="brand-mark" aria-hidden="true">
            <svg width="18" height="18" viewBox="0 0 18 18" fill="none"><path d="M3 14h12M3 9h8M3 4h10" stroke="#F8C53C" strokeWidth="2" strokeLinecap="round" /></svg>
          </span>
          <span><div className="brand-name">Screening Console</div><div className="brand-sub">Technical recruiting intelligence</div></span>
        </a>
        <nav className="nav" aria-label="Main">
          {nav("dashboard", "Ranking", hrefs.dashboard(), model?.eligible.length)}
          {nav("compare", "Compare", hrefs.compare(selected), selected.length || undefined)}
          {nav("rejected", "Rejected", hrefs.rejected(), model?.rejected.length)}
          {nav("failed", "Failed", hrefs.failed(), model?.failed.length)}
        </nav>
      </div>
      <main>
        {error ? <div className="page"><ErrorState error={error} onRetry={load} /></div> : !model ? <div className="page"><Loading /></div> : (
          <>
            {route.name === "dashboard" && <Dashboard model={model} selected={selected} onToggle={toggle} />}
            {route.name === "candidate" && <CandidateDetail model={model} file={route.file} selected={selected} onToggle={toggle} />}
            {route.name === "compare" && <Compare model={model} files={route.files} />}
            {route.name === "rejected" && <Rejected model={model} />}
            {route.name === "failed" && <Failed model={model} />}
          </>
        )}
      </main>
      {model && source?.has_results ? <footer className="foot muted">Results source: {source.source}. Generated by the screening pipeline; this console only displays them.</footer> : null}
      {model && route.name !== "compare" && <SelectionTray selected={selected} byFile={model.byFile} onRemove={toggle} onClear={() => setSelected([])} />}
    </div>
  );
}
